In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('iris.csv')

In [4]:
df

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.size

750

In [6]:
df.shape

(150, 5)

In [8]:
df.describe()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   148.000000    149.000000   149.000000
mean       8.043333     3.052027      4.511409     1.944966
std       19.956592     0.433224      8.996204     8.976948
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max      225.000000     4.400000    111.500000   110.400000

In [9]:
df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [10]:
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

In [12]:
df.isna().sum()

Sepal.Length    0
Sepal.Width     2
Petal.Length    1
Petal.Width     1
Species         0
dtype: int64

In [13]:
df2 = df.dropna()

In [14]:
df2.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [15]:
m = df['Sepal.Width'].mean()
m

np.float64(3.0520270270270276)

In [16]:
df['Sepal.Width'].fillna(m)

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: Sepal.Width, Length: 150, dtype: float64

In [17]:
df.groupby('Species').mean()

            Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species
setosa            11.606     3.427083      3.706122     2.493878
versicolor         5.936     2.770000      4.260000     1.326000
virginica          6.588     2.974000      5.552000     2.026000

In [18]:
df.groupby('Species').agg({'Sepal.Length': ['mean','median','std'], 'Petal.Length': ['mean','median','std'],
                           'Sepal.Width': ['mean','median','std'], 'Petal.Width': ['mean','median','std']})

           Sepal.Length                   Petal.Length                    \
                   mean median        std         mean median        std
Species
setosa           11.606    5.0  34.507062     3.706122   1.50  15.720918
versicolor        5.936    5.9   0.516171     4.260000   4.35   0.469911
virginica         6.588    6.5   0.635880     5.552000   5.55   0.551895

           Sepal.Width                  Petal.Width
                  mean median       std        mean median        std
Species
setosa        3.427083    3.4  0.375720    2.493878    0.2  15.736640
versicolor    2.770000    2.8  0.313798    1.326000    1.3   0.197753
virginica     2.974000    3.0  0.322497    2.026000    2.0   0.274650

In [19]:
avg = df['Sepal.Length'].mean()
avg

np.float64(8.043333333333333)

In [20]:
std = df['Sepal.Length'].std()
std

np.float64(19.95659187547103)

In [21]:
df[df['Sepal.Length']> avg]

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
19         115.1          3.8           1.5          0.3  setosa
35         225.0          3.2           1.2          0.2  setosa

In [22]:
df[df['Sepal.Width']> 3.0]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
6             4.6          3.4           1.4          0.3     setosa
..            ...          ...           ...          ...        ...
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
148           6.2          3.4           5.4          2.3  virginica

[66 rows x 5 columns]

In [23]:
lower = avg - 2 * std
lower

np.float64(-31.869850417608728)

In [24]:
upper = avg + 2 * std
upper

np.float64(47.95651708427539)

In [25]:
df[(df['Sepal.Length'] > lower) & (df['Sepal.Length'] < upper)]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[148 rows x 5 columns]

In [26]:
df[(df['Sepal.Length'] < lower) & (df['Sepal.Length'] > upper)]

Empty DataFrame
Columns: [Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species]
Index: []

In [27]:
Q1 = df['Sepal.Length'].quantile(0.25)
Q3 = df['Sepal.Length'].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR
df[df['Sepal.Length']>upper]

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
19         115.1          3.8           1.5          0.3  setosa
35         225.0          3.2           1.2          0.2  setosa